services:
  subredditfeed:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - BOT_USERNAME=${BOT_USERNAME}
      - USER_AGENT=${USER_AGENT}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - SUBREDDIT=${SUBREDDIT}
